---
json_rpc_url: "http://127.0.0.1:8899"
websocket_url: ""
keypair_path: /home/sandworm/.config/solana/test1.json
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed
